
export const TYPES={
    UserRepository  : Symbol.for("UserRepository"),
    OtpRepository : Symbol.for("OtpRepositiry"),
    PasswordService : Symbol.for("PassWordService"),
    OtpService : Symbol.for("OtpService"),
    AuthService : Symbol.for("AuthService"),
    AuthController : Symbol.for("AuthController"),
    AuthRoutes : Symbol.for("AuthRoutes"),
    ServiceRepository : Symbol.for("ServiceRepository"),
    SubServiceRepository: Symbol.for("SubServiceRepository"),
    UserService : Symbol.for("UserService"),
    UserController : Symbol.for("UserController"),
    UserRoutes : Symbol.for("UserRoutes"),
    AdminService : Symbol.for("AdminService"),
    AdminController : Symbol.for("AdminController"),
    AdminRoutes : Symbol.for("AdminRoutes"),
    TimeSlotController : Symbol.for("TimeSlotController"),
    TimeSlotService : Symbol.for("TimeSlotService"),
    PartnerRoutes : Symbol.for("PartnerRoutes"),
    BookingRepository : Symbol.for("BookingRepository"),
    BookingService : Symbol.for("BookingService"),
    BookingController : Symbol.for("BookingController"),
    BookingRoutes : Symbol.for("BookingRoutes"),
    WalletRepository:Symbol.for("WalletRepository"),
    WalletService:Symbol.for("WalletService"),
    WalletController:Symbol.for("WalletController"),
    WalletRoutes : Symbol.for("WalletRoutes"),
    TransactionRepository: Symbol.for("TransactionRepository"),
    TransactionService: Symbol.for("TransactionService"),
    TransactionController: Symbol.for("TransactionController"),
    TransactionRoutes: Symbol.for("TransactionRoutes")
}