export const TYPES={
    UserRepository  : Symbol.for("UserRepository"),
    OtpRepository : Symbol.for("OtpRepositiry"),
    PasswordService : Symbol.for("PassWordService"),
    OtpService : Symbol.for("OtpService"),
    AuthService : Symbol.for("AuthService"),
    AuthController : Symbol.for("AuthController"),
    AuthRoutes : Symbol.for("AuthRoutes"),
    ServiceRepository : Symbol.for("ServiceRepository"),
    SubServiceRepository: Symbol.for("SubServiceRepository"),
    UserService : Symbol.for("UserService"),
    UserController : Symbol.for("UserController"),
    UserRoutes : Symbol.for("UserRoutes"),
    AdminService : Symbol.for("AdminService"),
    AdminController : Symbol.for("AdminController"),
    AdminRoutes : Symbol.for("AdminRoutes"),
    TimeSlotController : Symbol.for("TimeSlotController"),
    TimeSlotService : Symbol.for("TimeSlotService"),
    PartnerRoutes : Symbol.for("PartnerRoutes"),
}