name: Backend CI/CD Pipeline (Build Locally, Deploy Dist Only)

on:
  push:
    branches: [main]  # Trigger on push to main branch

jobs:
  build:
    name: Build and Prepare Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Create deployment archive
        run: |
          tar -czf dist.tar.gz dist package.json package-lock.json

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: dist.tar.gz

  deploy:
    name: Deploy to AWS EC2
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-dist
          path: .

      - name: Copy build to EC2 via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "dist.tar.gz"
          target: "/home/ubuntu/fixomojo-backend"

      - name: Deploy on EC2 (extract + restart)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/fixomojo-backend
            tar -xzf dist.tar.gz
            rm dist.tar.gz
            npm install --production
            pm2 restart fixomojo || pm2 start dist/server.js --name fixomojo
            echo "✅ Deployment completed successfully!"
